import type { z } from 'zod';
import { pool } from '../../db/pool.js';
import { HttpError } from '../../lib/http-error.js';
import { paginationMeta } from '../../lib/pagination.js';
import { assertBusinessUnitPermission } from '../access/authorization.service.js';
import { writeAuditEvent } from '../audit/admin-audit.service.js';
import { createEmployeeSchema, employeeListQuerySchema, updateEmployeeSchema } from './admin-employee.schemas.js';

type ListQuery=z.infer<typeof employeeListQuerySchema>;type CreateInput=z.infer<typeof createEmployeeSchema>;type UpdateInput=z.infer<typeof updateEmployeeSchema>;
type Row={id:string;user_id:string|null;employee_number:string|null;display_name:string;email:string|null;phone:string|null;job_title:string|null;hire_date:string|null;termination_date:string|null;status:'active'|'inactive'|'terminated';notes:string|null;created_at:Date;updated_at:Date};
function map(r:Row){return{id:r.id,userId:r.user_id,employeeNumber:r.employee_number,displayName:r.display_name,email:r.email,phone:r.phone,jobTitle:r.job_title,hireDate:r.hire_date,terminationDate:r.termination_date,status:r.status,notes:r.notes,createdAt:r.created_at,updatedAt:r.updated_at};}
async function validateUser(userId:string|null|undefined){if(!userId)return;const result=await pool.query('SELECT 1 FROM users WHERE id=$1 AND status=\'active\'',[userId]);if(!result.rows[0])throw new HttpError(400,'INVALID_USER','Linked user does not exist or is disabled.');}
export async function listEmployees(userId:string,businessUnitId:string,q:ListQuery){await assertBusinessUnitPermission(userId,businessUnitId,'employees.read');const result=await pool.query<Row>(`SELECT * FROM employees WHERE business_unit_id=$1 AND ($2::text IS NULL OR status=$2) AND ($3::text IS NULL OR display_name ILIKE '%'||$3||'%' OR COALESCE(employee_number,'') ILIKE '%'||$3||'%' OR COALESCE(email::text,'') ILIKE '%'||$3||'%') ORDER BY display_name LIMIT $4 OFFSET $5`,[businessUnitId,q.status??null,q.search||null,q.limit,q.offset]);return{data:result.rows.map(map),meta:paginationMeta(q,result.rows.length)};}
export async function createEmployee(userId:string,businessUnitId:string,input:CreateInput){await assertBusinessUnitPermission(userId,businessUnitId,'employees.write');await validateUser(input.userId);const result=await pool.query<Row>(`INSERT INTO employees (business_unit_id,user_id,employee_number,display_name,email,phone,job_title,hire_date,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[businessUnitId,input.userId??null,input.employeeNumber??null,input.displayName,input.email??null,input.phone??null,input.jobTitle??null,input.hireDate??null,input.notes??null]);const row=result.rows[0];if(!row)throw new HttpError(500,'EMPLOYEE_CREATE_FAILED','Employee could not be created.');await writeAuditEvent({actorUserId:userId,businessUnitId,action:'employee.created',resourceType:'employee',resourceId:row.id,metadata:{displayName:row.display_name}});return map(row);}
export async function updateEmployee(userId:string,businessUnitId:string,employeeId:string,input:UpdateInput){await assertBusinessUnitPermission(userId,businessUnitId,'employees.write');if(input.userId!==undefined)await validateUser(input.userId);const currentResult=await pool.query<Row>('SELECT * FROM employees WHERE id=$1 AND business_unit_id=$2',[employeeId,businessUnitId]);const c=currentResult.rows[0];if(!c)throw new HttpError(404,'EMPLOYEE_NOT_FOUND','Employee not found.');const status=input.status??c.status;const terminationDate=input.terminationDate===undefined?(status==='terminated'&&!c.termination_date?new Date().toISOString().slice(0,10):c.termination_date):input.terminationDate;const result=await pool.query<Row>(`UPDATE employees SET user_id=$3,employee_number=$4,display_name=$5,email=$6,phone=$7,job_title=$8,hire_date=$9,termination_date=$10,status=$11,notes=$12 WHERE id=$1 AND business_unit_id=$2 RETURNING *`,[employeeId,businessUnitId,input.userId===undefined?c.user_id:input.userId,input.employeeNumber===undefined?c.employee_number:input.employeeNumber,input.displayName??c.display_name,input.email===undefined?c.email:input.email,input.phone===undefined?c.phone:input.phone,input.jobTitle===undefined?c.job_title:input.jobTitle,input.hireDate===undefined?c.hire_date:input.hireDate,terminationDate,status,input.notes===undefined?c.notes:input.notes]);const row=result.rows[0]!;await writeAuditEvent({actorUserId:userId,businessUnitId,action:'employee.updated',resourceType:'employee',resourceId:employeeId,metadata:{status:row.status}});return map(row);}
