import { Router } from 'express';
import { adminAccessRouter } from '../modules/access/admin-access.routes.js';
import { adminOverviewRouter } from '../modules/admin/admin-overview.routes.js';
import { adminAuditRouter } from '../modules/audit/admin-audit.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';
import { bookkeepingAccountResponseRouter } from '../modules/bookkeeping/account-response.routes.js';
import { bookkeepingAccountRollupRouter } from '../modules/bookkeeping/account-rollup.routes.js';
import { bookkeepingAttachmentRouter } from '../modules/bookkeeping/attachment.routes.js';
import { bookkeepingRouter } from '../modules/bookkeeping/bookkeeping.routes.js';
import { bookkeepingCompletionRouter } from '../modules/bookkeeping/completion.routes.js';
import { bookkeepingFrontendCompatRouter } from '../modules/bookkeeping/frontend-compat.routes.js';
import { bookkeepingLegacyWorkflowRouter } from '../modules/bookkeeping/legacy-workflow.routes.js';
import { bookkeepingMileageCompatRouter } from '../modules/bookkeeping/mileage-compat.routes.js';
import { bookkeepingSpecialTransactionRouter } from '../modules/bookkeeping/special-transaction.routes.js';
import { bookkeepingTransactionListRouter } from '../modules/bookkeeping/transaction-list.routes.js';
import { bookkeepingTransactionRouter } from '../modules/bookkeeping/transaction.routes.js';
import { bookkeepingVehicleRouter } from '../modules/bookkeeping/bookkeeping-vehicle.routes.js';
import { adminBusinessUnitRouter } from '../modules/business-units/admin-business-unit.routes.js';
import { businessUnitRouter } from '../modules/business-units/business-unit.routes.js';
import { customerPortalRouter } from '../modules/customer-portal/customer-portal.routes.js';
import { healthRouter } from '../modules/health/health.routes.js';
import { adminIntegrationRouter } from '../modules/integrations/admin-integration.routes.js';
import { adminIntercompanyRouter } from '../modules/intercompany/admin-intercompany.routes.js';
import { adminLegalEntityRouter } from '../modules/legal-entities/admin-legal-entity.routes.js';
import { adminNotificationRouter } from '../modules/notifications/admin-notification.routes.js';
import { textBeeWebhookRouter } from '../modules/notifications/textbee-webhook.routes.js';
import { adminConsolidatedReportRouter } from '../modules/reporting/admin-reporting.routes.js';
import { adminSiteRouter } from '../modules/sites/admin-site.routes.js';
import { publicSiteRouter } from '../modules/sites/public-site.routes.js';
import { adminUserRouter } from '../modules/users/admin-user.routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/customer', customerPortalRouter);
apiRouter.use('/business-units', businessUnitRouter);
apiRouter.use('/bookkeeping/transactions', bookkeepingSpecialTransactionRouter);
apiRouter.use('/bookkeeping/transactions', bookkeepingTransactionListRouter);
apiRouter.use('/bookkeeping/transactions', bookkeepingTransactionRouter);
apiRouter.use('/bookkeeping', bookkeepingAttachmentRouter);
apiRouter.use('/bookkeeping', bookkeepingAccountRollupRouter);
apiRouter.use('/bookkeeping', bookkeepingAccountResponseRouter);
apiRouter.use('/bookkeeping', bookkeepingMileageCompatRouter);
apiRouter.use('/bookkeeping', bookkeepingVehicleRouter);
apiRouter.use('/bookkeeping', bookkeepingLegacyWorkflowRouter);
apiRouter.use('/bookkeeping', bookkeepingFrontendCompatRouter);
apiRouter.use('/bookkeeping', bookkeepingCompletionRouter);
apiRouter.use('/bookkeeping', bookkeepingRouter);
apiRouter.use('/public/sites', publicSiteRouter);
apiRouter.use('/webhooks/textbee', textBeeWebhookRouter);

apiRouter.use('/admin/overview', adminOverviewRouter);
apiRouter.use('/admin/access', adminAccessRouter);
apiRouter.use('/admin/audit', adminAuditRouter);
apiRouter.use('/admin/legal-entities', adminLegalEntityRouter);
apiRouter.use('/admin/business-units', adminBusinessUnitRouter);
apiRouter.use('/admin/users', adminUserRouter);
apiRouter.use('/admin/sites', adminSiteRouter);
apiRouter.use('/admin/reporting', adminConsolidatedReportRouter);
apiRouter.use('/admin/intercompany', adminIntercompanyRouter);
apiRouter.use('/admin/notifications', adminNotificationRouter);
apiRouter.use('/admin/integrations', adminIntegrationRouter);
