import type { z } from 'zod';
import { pool } from '../../db/pool.js';
import { HttpError } from '../../lib/http-error.js';
import { paginationMeta } from '../../lib/pagination.js';
import { assertBusinessUnitPermission } from '../access/authorization.service.js';
import { writeAuditEvent } from '../audit/admin-audit.service.js';
import { createMileageLogSchema, mileageListQuerySchema } from './admin-mileage.schemas.js';

type ListQuery=z.infer<typeof mileageListQuerySchema>;type CreateInput=z.infer<typeof createMileageLogSchema>;
type Row={id:string;vehicle_id:string;employee_id:string|null;start_odometer:string;end_odometer:string;miles:string;purpose:string;started_at:Date;ended_at:Date|null;notes:string|null;created_at:Date};
function map(r:Row){return{id:r.id,vehicleId:r.vehicle_id,employeeId:r.employee_id,startOdometer:Number(r.start_odometer),endOdometer:Number(r.end_odometer),miles:Number(r.miles),purpose:r.purpose,startedAt:r.started_at,endedAt:r.ended_at,notes:r.notes,createdAt:r.created_at};}
async function validateVehicle(businessUnitId:string,vehicleId:string){const result=await pool.query<{current_odometer:string|null}>('SELECT current_odometer::text FROM vehicles WHERE id=$1 AND business_unit_id=$2',[vehicleId,businessUnitId]);const row=result.rows[0];if(!row)throw new HttpError(400,'INVALID_VEHICLE','Vehicle does not belong to this business unit.');return row.current_odometer===null?null:Number(row.current_odometer);}
async function validateEmployee(businessUnitId:string,employeeId:string|null|undefined){if(!employeeId)return;const result=await pool.query('SELECT 1 FROM employees WHERE id=$1 AND business_unit_id=$2',[employeeId,businessUnitId]);if(!result.rows[0])throw new HttpError(400,'INVALID_EMPLOYEE','Employee does not belong to this business unit.');}
export async function listMileageLogs(userId:string,businessUnitId:string,q:ListQuery){await assertBusinessUnitPermission(userId,businessUnitId,'mileage.read');const result=await pool.query<Row>(`SELECT id,vehicle_id,employee_id,start_odometer::text,end_odometer::text,miles::text,purpose,started_at,ended_at,notes,created_at FROM mileage_logs WHERE business_unit_id=$1 AND ($2::uuid IS NULL OR vehicle_id=$2) AND ($3::uuid IS NULL OR employee_id=$3) AND ($4::timestamptz IS NULL OR started_at >= $4) AND ($5::timestamptz IS NULL OR started_at <= $5) ORDER BY started_at DESC LIMIT $6 OFFSET $7`,[businessUnitId,q.vehicleId??null,q.employeeId??null,q.from??null,q.to??null,q.limit,q.offset]);return{data:result.rows.map(map),meta:paginationMeta(q,result.rows.length)};}
export async function createMileageLog(userId:string,businessUnitId:string,input:CreateInput){await assertBusinessUnitPermission(userId,businessUnitId,'mileage.write');const currentOdometer=await validateVehicle(businessUnitId,input.vehicleId);await validateEmployee(businessUnitId,input.employeeId);if(currentOdometer!==null&&input.startOdometer<currentOdometer)throw new HttpError(409,'ODOMETER_ROLLBACK','startOdometer cannot be less than the vehicle current odometer.');const client=await pool.connect();try{await client.query('BEGIN');const result=await client.query<Row>(`INSERT INTO mileage_logs (business_unit_id,vehicle_id,employee_id,start_odometer,end_odometer,purpose,started_at,ended_at,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,vehicle_id,employee_id,start_odometer::text,end_odometer::text,miles::text,purpose,started_at,ended_at,notes,created_at`,[businessUnitId,input.vehicleId,input.employeeId??null,input.startOdometer,input.endOdometer,input.purpose,input.startedAt,input.endedAt??null,input.notes??null]);const row=result.rows[0];if(!row)throw new HttpError(500,'MILEAGE_CREATE_FAILED','Mileage log could not be created.');await client.query(`UPDATE vehicles SET current_odometer=GREATEST(COALESCE(current_odometer,0),$2) WHERE id=$1`,[input.vehicleId,input.endOdometer]);await client.query('COMMIT');await writeAuditEvent({actorUserId:userId,businessUnitId,action:'mileage.created',resourceType:'mileage_log',resourceId:row.id,metadata:{vehicleId:input.vehicleId,miles:Number(row.miles)}});return map(row);}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
