import { pool } from '../../db/pool.js';
import { HttpError } from '../../lib/http-error.js';
import { writeAuditEvent } from '../audit/admin-audit.service.js';
import { requestPasswordReset } from '../auth/password-management.service.js';

type Metadata={ipAddress:string|null;userAgent:string|null};
type SessionRow={id:string;expires_at:Date;last_seen_at:Date;revoked_at:Date|null;ip_address:string|null;user_agent:string|null;created_at:Date};

async function assertTargetPermission(actorUserId:string,targetUserId:string,permissionKey:string){const result=await pool.query<{allowed:boolean}>(`SELECT EXISTS (SELECT 1 FROM user_role_assignments actor_ura JOIN roles actor_role ON actor_role.id=actor_ura.role_id JOIN role_permissions rp ON rp.role_id=actor_role.id JOIN permissions p ON p.id=rp.permission_id LEFT JOIN user_role_assignments target_ura ON target_ura.user_id=$2 LEFT JOIN business_units target_bu ON target_bu.id=target_ura.business_unit_id WHERE actor_ura.user_id=$1 AND p.key=$3 AND ((actor_role.scope='platform' AND actor_ura.legal_entity_id IS NULL AND actor_ura.business_unit_id IS NULL) OR (actor_role.scope='legal_entity' AND (target_ura.legal_entity_id=actor_ura.legal_entity_id OR target_bu.legal_entity_id=actor_ura.legal_entity_id)) OR (actor_role.scope='business_unit' AND target_ura.business_unit_id=actor_ura.business_unit_id))) AS allowed`,[actorUserId,targetUserId,permissionKey]);if(!result.rows[0]?.allowed)throw new HttpError(403,'FORBIDDEN','You do not have permission to manage this user in the requested scope.');}
export async function listUserSessions(actorUserId:string,targetUserId:string){await assertTargetPermission(actorUserId,targetUserId,'sessions.read');const result=await pool.query<SessionRow>(`SELECT id,expires_at,last_seen_at,revoked_at,ip_address::text,user_agent,created_at FROM user_sessions WHERE user_id=$1 AND expires_at > now()-interval '30 days' ORDER BY created_at DESC`,[targetUserId]);return result.rows.map(r=>({id:r.id,active:r.revoked_at===null&&r.expires_at>new Date(),expiresAt:r.expires_at,lastSeenAt:r.last_seen_at,revokedAt:r.revoked_at,ipAddress:r.ip_address,userAgent:r.user_agent,createdAt:r.created_at}));}
export async function revokeUserSession(actorUserId:string,targetUserId:string,sessionId:string,metadata:Metadata){await assertTargetPermission(actorUserId,targetUserId,'sessions.manage');const result=await pool.query<{id:string}>(`UPDATE user_sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE id=$1 AND user_id=$2 RETURNING id`,[sessionId,targetUserId]);if(!result.rows[0])throw new HttpError(404,'SESSION_NOT_FOUND','Session not found.');await writeAuditEvent({actorUserId,action:'user.session.revoked',resourceType:'user_session',resourceId:sessionId,metadata:{targetUserId},ipAddress:metadata.ipAddress,userAgent:metadata.userAgent});}
export async function revokeAllUserSessions(actorUserId:string,targetUserId:string,metadata:Metadata){await assertTargetPermission(actorUserId,targetUserId,'sessions.manage');const result=await pool.query(`UPDATE user_sessions SET revoked_at=COALESCE(revoked_at,now()) WHERE user_id=$1 AND revoked_at IS NULL AND expires_at>now()`,[targetUserId]);await writeAuditEvent({actorUserId,action:'user.sessions.revoked_all',resourceType:'user',resourceId:targetUserId,metadata:{count:result.rowCount??0},ipAddress:metadata.ipAddress,userAgent:metadata.userAgent});return result.rowCount??0;}
export async function issueUserPasswordReset(actorUserId:string,targetUserId:string,metadata:Metadata){await assertTargetPermission(actorUserId,targetUserId,'users.write');const result=await pool.query<{email:string}>('SELECT email::text AS email FROM users WHERE id=$1 AND status=\'active\'',[targetUserId]);const user=result.rows[0];if(!user)throw new HttpError(404,'USER_NOT_FOUND','Active user not found.');await requestPasswordReset(user.email,metadata);await writeAuditEvent({actorUserId,action:'user.password_reset.requested',resourceType:'user',resourceId:targetUserId,ipAddress:metadata.ipAddress,userAgent:metadata.userAgent});return{accepted:true};}
