import type { z } from 'zod';
import { pool } from '../../db/pool.js';
import { HttpError } from '../../lib/http-error.js';
import { assertBusinessUnitPermission } from '../access/authorization.service.js';
import { listAccessibleBusinessUnits } from '../business-units/admin-business-unit.service.js';
import { consolidatedReportQuerySchema, reportRangeSchema, trialBalanceQuerySchema } from './admin-reporting.schemas.js';

type Range=z.infer<typeof reportRangeSchema>;type TrialQuery=z.infer<typeof trialBalanceQuerySchema>;type ConsolidatedQuery=z.infer<typeof consolidatedReportQuerySchema>;
function rangeParams(q:Range){return[q.from??null,q.to??null] as const;}
export async function getBusinessUnitSummary(userId:string,businessUnitId:string,q:Range){await assertBusinessUnitPermission(userId,businessUnitId,'reporting.read');const [from,to]=rangeParams(q);const result=await pool.query<{customers:string;work_orders:string;invoice_total:string;invoice_paid:string;payments:string;expenses:string;revenue:string}>(`SELECT (SELECT count(*)::text FROM customers WHERE business_unit_id=$1 AND status='active') AS customers,(SELECT count(*)::text FROM work_orders WHERE business_unit_id=$1 AND ($2::date IS NULL OR created_at::date >= $2) AND ($3::date IS NULL OR created_at::date <= $3)) AS work_orders,(SELECT COALESCE(sum(total_cents),0)::text FROM invoices WHERE business_unit_id=$1 AND status<>'void' AND ($2::date IS NULL OR created_at::date >= $2) AND ($3::date IS NULL OR created_at::date <= $3)) AS invoice_total,(SELECT COALESCE(sum(amount_paid_cents),0)::text FROM invoices WHERE business_unit_id=$1 AND status<>'void' AND ($2::date IS NULL OR created_at::date >= $2) AND ($3::date IS NULL OR created_at::date <= $3)) AS invoice_paid,(SELECT COALESCE(sum(amount_cents),0)::text FROM payments WHERE business_unit_id=$1 AND status='completed' AND ($2::date IS NULL OR received_at::date >= $2) AND ($3::date IS NULL OR received_at::date <= $3)) AS payments,(SELECT COALESCE(sum(amount_cents),0)::text FROM expenses WHERE business_unit_id=$1 AND status='posted' AND ($2::date IS NULL OR expense_date >= $2) AND ($3::date IS NULL OR expense_date <= $3)) AS expenses,(SELECT COALESCE(sum(amount_cents),0)::text FROM revenue_records WHERE business_unit_id=$1 AND status='posted' AND ($2::date IS NULL OR revenue_date >= $2) AND ($3::date IS NULL OR revenue_date <= $3)) AS revenue`,[businessUnitId,from,to]);const r=result.rows[0];if(!r)throw new HttpError(500,'REPORT_FAILED','Report could not be generated.');return{range:{from,to},customers:Number(r.customers),workOrders:Number(r.work_orders),invoices:{totalCents:Number(r.invoice_total),paidCents:Number(r.invoice_paid),outstandingCents:Number(r.invoice_total)-Number(r.invoice_paid)},paymentsCents:Number(r.payments),postedExpensesCents:Number(r.expenses),postedRevenueCents:Number(r.revenue),netOperatingCents:Number(r.revenue)-Number(r.expenses)};}
export async function getTrialBalance(userId:string,businessUnitId:string,q:TrialQuery){await assertBusinessUnitPermission(userId,businessUnitId,'reporting.read');const result=await pool.query<{id:string;code:string;name:string;account_type:string;debits:string;credits:string}>(`SELECT a.id,a.code,a.name,a.account_type,COALESCE(sum(jl.debit_cents),0)::text AS debits,COALESCE(sum(jl.credit_cents),0)::text AS credits FROM ledger_accounts a JOIN business_units bu ON bu.legal_entity_id=a.legal_entity_id LEFT JOIN journal_entries je ON je.business_unit_id=bu.id AND je.status IN ('posted','reversed') AND ($2::date IS NULL OR je.entry_date <= $2) LEFT JOIN journal_lines jl ON jl.journal_entry_id=je.id AND jl.account_id=a.id WHERE bu.id=$1 GROUP BY a.id,a.code,a.name,a.account_type ORDER BY a.code`,[businessUnitId,q.asOf??null]);return{asOf:q.asOf??null,accounts:result.rows.map(r=>({id:r.id,code:r.code,name:r.name,accountType:r.account_type,debitsCents:Number(r.debits),creditsCents:Number(r.credits),netCents:Number(r.debits)-Number(r.credits)}))};}
export async function getConsolidatedSummary(userId:string,q:ConsolidatedQuery){const units=await listAccessibleBusinessUnits(userId,true);const filtered=q.legalEntityId?units.filter(u=>u.legalEntity.id===q.legalEntityId):units;if(filtered.length===0)return{range:{from:q.from??null,to:q.to??null},businessUnits:[],totals:{invoiceTotalCents:0,invoicePaidCents:0,paymentsCents:0,postedExpensesCents:0,postedRevenueCents:0,netOperatingCents:0}};const reports=[];for(const unit of filtered){try{reports.push({businessUnit:unit,summary:await getBusinessUnitSummary(userId,unit.id,{from:q.from,to:q.to})});}catch(error){if(error instanceof HttpError&&error.statusCode===403)continue;throw error;}}const totals=reports.reduce((a,r)=>({invoiceTotalCents:a.invoiceTotalCents+r.summary.invoices.totalCents,invoicePaidCents:a.invoicePaidCents+r.summary.invoices.paidCents,paymentsCents:a.paymentsCents+r.summary.paymentsCents,postedExpensesCents:a.postedExpensesCents+r.summary.postedExpensesCents,postedRevenueCents:a.postedRevenueCents+r.summary.postedRevenueCents,netOperatingCents:a.netOperatingCents+r.summary.netOperatingCents}),{invoiceTotalCents:0,invoicePaidCents:0,paymentsCents:0,postedExpensesCents:0,postedRevenueCents:0,netOperatingCents:0});return{range:{from:q.from??null,to:q.to??null},businessUnits:reports,totals};}
