import type { PoolClient } from 'pg';
import type { z } from 'zod';
import { pool } from '../../db/pool.js';
import { HttpError } from '../../lib/http-error.js';
import { paginationMeta } from '../../lib/pagination.js';
import { assertBusinessUnitPermission, assertLegalEntityPermission } from '../access/authorization.service.js';
import { writeAuditEvent } from '../audit/admin-audit.service.js';
import {
  accountListQuerySchema,
  accountingEventListQuerySchema,
  createAccountSchema,
  createJournalSchema,
  postAccountingEventSchema,
  reverseJournalSchema,
  updateAccountSchema,
  updateJournalSchema,
  journalListQuerySchema,
} from './admin-bookkeeping.schemas.js';

type AccountListQuery = z.infer<typeof accountListQuerySchema>;
type CreateAccountInput = z.infer<typeof createAccountSchema>;
type UpdateAccountInput = z.infer<typeof updateAccountSchema>;
type JournalListQuery = z.infer<typeof journalListQuerySchema>;
type CreateJournalInput = z.infer<typeof createJournalSchema>;
type UpdateJournalInput = z.infer<typeof updateJournalSchema>;
type ReverseJournalInput = z.infer<typeof reverseJournalSchema>;
type EventListQuery = z.infer<typeof accountingEventListQuerySchema>;
type PostEventInput = z.infer<typeof postAccountingEventSchema>;
type JournalLineInput = CreateJournalInput['lines'][number];

type UnitContext = { business_unit_id: string; legal_entity_id: string; business_unit_name: string; legal_entity_name: string };
type AccountRow = { id:string;parent_account_id:string|null;code:string;name:string;account_type:'asset'|'liability'|'equity'|'revenue'|'expense';subtype:string|null;status:'active'|'inactive';created_at:Date;updated_at:Date };
type JournalRow = { id:string;legal_entity_id:string;business_unit_id:string;entry_number:string;entry_date:string;description:string;status:'draft'|'posted'|'reversed';source_type:string|null;source_id:string|null;posted_at:Date|null;reversed_entry_id:string|null;created_by_user_id:string|null;created_at:Date;updated_at:Date };
type JournalLineRow = { id:string;account_id:string;account_code:string;account_name:string;debit_cents:string;credit_cents:string;memo:string|null };
type EventRow = { id:string;event_type:string;source_type:string;source_id:string;amount_cents:string|null;status:'pending'|'posted'|'failed'|'ignored';journal_entry_id:string|null;metadata:Record<string,unknown>;created_at:Date;updated_at:Date };

async function unitContext(businessUnitId:string):Promise<UnitContext>{
  const result=await pool.query<UnitContext>(`SELECT bu.id AS business_unit_id,bu.legal_entity_id,bu.name AS business_unit_name,le.display_name AS legal_entity_name FROM business_units bu JOIN legal_entities le ON le.id=bu.legal_entity_id WHERE bu.id=$1`,[businessUnitId]);
  const row=result.rows[0];if(!row)throw new HttpError(404,'BUSINESS_UNIT_NOT_FOUND','Business unit not found.');return row;
}
function mapAccount(r:AccountRow){return{id:r.id,parentAccountId:r.parent_account_id,code:r.code,name:r.name,accountType:r.account_type,subtype:r.subtype,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at};}
function mapJournal(r:JournalRow){return{id:r.id,legalEntityId:r.legal_entity_id,businessUnitId:r.business_unit_id,entryNumber:r.entry_number,entryDate:r.entry_date,description:r.description,status:r.status,sourceType:r.source_type,sourceId:r.source_id,postedAt:r.posted_at,reversedEntryId:r.reversed_entry_id,createdByUserId:r.created_by_user_id,createdAt:r.created_at,updatedAt:r.updated_at};}
function mapLine(r:JournalLineRow){return{id:r.id,accountId:r.account_id,accountCode:r.account_code,accountName:r.account_name,debitCents:Number(r.debit_cents),creditCents:Number(r.credit_cents),memo:r.memo};}
function mapEvent(r:EventRow){return{id:r.id,eventType:r.event_type,sourceType:r.source_type,sourceId:r.source_id,amountCents:r.amount_cents===null?null:Number(r.amount_cents),status:r.status,journalEntryId:r.journal_entry_id,metadata:r.metadata,createdAt:r.created_at,updatedAt:r.updated_at};}

async function validateParentAccount(legalEntityId:string,parentAccountId:string|null|undefined){if(!parentAccountId)return;const result=await pool.query('SELECT 1 FROM ledger_accounts WHERE id=$1 AND legal_entity_id=$2',[parentAccountId,legalEntityId]);if(!result.rows[0])throw new HttpError(400,'INVALID_PARENT_ACCOUNT','Parent account does not belong to the legal entity.');}

export async function listAccounts(userId:string,businessUnitId:string,q:AccountListQuery){const context=await unitContext(businessUnitId);await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.read');const result=await pool.query<AccountRow>(`SELECT id,parent_account_id,code,name,account_type,subtype,status,created_at,updated_at FROM ledger_accounts WHERE legal_entity_id=$1 AND ($2::text IS NULL OR account_type=$2) AND ($3::boolean OR status='active') AND ($4::text IS NULL OR code ILIKE '%'||$4||'%' OR name ILIKE '%'||$4||'%') ORDER BY code LIMIT $5 OFFSET $6`,[context.legal_entity_id,q.accountType??null,q.includeInactive??false,q.search||null,q.limit,q.offset]);return{data:result.rows.map(mapAccount),meta:paginationMeta(q,result.rows.length),legalEntityId:context.legal_entity_id};}
export async function createAccount(userId:string,businessUnitId:string,input:CreateAccountInput){const context=await unitContext(businessUnitId);await assertLegalEntityPermission(userId,context.legal_entity_id,'bookkeeping.write');await validateParentAccount(context.legal_entity_id,input.parentAccountId);const result=await pool.query<AccountRow>(`INSERT INTO ledger_accounts (legal_entity_id,parent_account_id,code,name,account_type,subtype) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,parent_account_id,code,name,account_type,subtype,status,created_at,updated_at`,[context.legal_entity_id,input.parentAccountId??null,input.code,input.name,input.accountType,input.subtype??null]);const row=result.rows[0];if(!row)throw new HttpError(500,'ACCOUNT_CREATE_FAILED','Account could not be created.');await writeAuditEvent({actorUserId:userId,legalEntityId:context.legal_entity_id,action:'bookkeeping.account.created',resourceType:'ledger_account',resourceId:row.id,metadata:{code:row.code,name:row.name}});return mapAccount(row);}
export async function updateAccount(userId:string,businessUnitId:string,accountId:string,input:UpdateAccountInput){const context=await unitContext(businessUnitId);await assertLegalEntityPermission(userId,context.legal_entity_id,'bookkeeping.write');if(input.parentAccountId===accountId)throw new HttpError(400,'INVALID_PARENT_ACCOUNT','An account cannot be its own parent.');if(input.parentAccountId!==undefined)await validateParentAccount(context.legal_entity_id,input.parentAccountId);const current=await pool.query<AccountRow>(`SELECT id,parent_account_id,code,name,account_type,subtype,status,created_at,updated_at FROM ledger_accounts WHERE id=$1 AND legal_entity_id=$2`,[accountId,context.legal_entity_id]);const c=current.rows[0];if(!c)throw new HttpError(404,'ACCOUNT_NOT_FOUND','Account not found.');const result=await pool.query<AccountRow>(`UPDATE ledger_accounts SET parent_account_id=$3,code=$4,name=$5,subtype=$6,status=$7 WHERE id=$1 AND legal_entity_id=$2 RETURNING id,parent_account_id,code,name,account_type,subtype,status,created_at,updated_at`,[accountId,context.legal_entity_id,input.parentAccountId===undefined?c.parent_account_id:input.parentAccountId,input.code??c.code,input.name??c.name,input.subtype===undefined?c.subtype:input.subtype,input.status??c.status]);const row=result.rows[0]!;await writeAuditEvent({actorUserId:userId,legalEntityId:context.legal_entity_id,action:'bookkeeping.account.updated',resourceType:'ledger_account',resourceId:accountId,metadata:{code:row.code,status:row.status}});return mapAccount(row);}

async function insertLines(client:PoolClient,journalId:string,lines:JournalLineInput[]){for(let i=0;i<lines.length;i++){const line=lines[i]!;await client.query(`INSERT INTO journal_lines (journal_entry_id,account_id,debit_cents,credit_cents,memo) VALUES ($1,$2,$3,$4,$5)`,[journalId,line.accountId,line.debitCents,line.creditCents,line.memo??null]);}}
async function loadJournal(businessUnitId:string,journalId:string){const result=await pool.query<JournalRow>(`SELECT id,legal_entity_id,business_unit_id,entry_number,entry_date::text,description,status,source_type,source_id,posted_at,reversed_entry_id,created_by_user_id,created_at,updated_at FROM journal_entries WHERE id=$1 AND business_unit_id=$2`,[journalId,businessUnitId]);const row=result.rows[0];if(!row)throw new HttpError(404,'JOURNAL_NOT_FOUND','Journal entry not found.');const lines=await pool.query<JournalLineRow>(`SELECT jl.id,jl.account_id,a.code AS account_code,a.name AS account_name,jl.debit_cents::text,jl.credit_cents::text,jl.memo FROM journal_lines jl JOIN ledger_accounts a ON a.id=jl.account_id WHERE jl.journal_entry_id=$1 ORDER BY jl.created_at,jl.id`,[journalId]);return{...mapJournal(row),lines:lines.rows.map(mapLine)};}
export async function listJournals(userId:string,businessUnitId:string,q:JournalListQuery){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.read');const result=await pool.query<JournalRow>(`SELECT id,legal_entity_id,business_unit_id,entry_number,entry_date::text,description,status,source_type,source_id,posted_at,reversed_entry_id,created_by_user_id,created_at,updated_at FROM journal_entries WHERE business_unit_id=$1 AND ($2::text IS NULL OR status=$2) AND ($3::date IS NULL OR entry_date >= $3) AND ($4::date IS NULL OR entry_date <= $4) AND ($5::text IS NULL OR entry_number ILIKE '%'||$5||'%' OR description ILIKE '%'||$5||'%') ORDER BY entry_date DESC,created_at DESC LIMIT $6 OFFSET $7`,[businessUnitId,q.status??null,q.from??null,q.to??null,q.search||null,q.limit,q.offset]);return{data:result.rows.map(mapJournal),meta:paginationMeta(q,result.rows.length)};}
export async function getJournal(userId:string,businessUnitId:string,journalId:string){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.read');return loadJournal(businessUnitId,journalId);}
export async function createJournal(userId:string,businessUnitId:string,input:CreateJournalInput){const context=await unitContext(businessUnitId);await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.write');const client=await pool.connect();try{await client.query('BEGIN');const result=await client.query<{id:string}>(`INSERT INTO journal_entries (legal_entity_id,business_unit_id,entry_number,entry_date,description,source_type,source_id,created_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[context.legal_entity_id,businessUnitId,input.entryNumber,input.entryDate,input.description,input.sourceType??null,input.sourceId??null,userId]);const id=result.rows[0]?.id;if(!id)throw new HttpError(500,'JOURNAL_CREATE_FAILED','Journal entry could not be created.');await insertLines(client,id,input.lines);await client.query('COMMIT');await writeAuditEvent({actorUserId:userId,legalEntityId:context.legal_entity_id,businessUnitId,action:'bookkeeping.journal.created',resourceType:'journal_entry',resourceId:id,metadata:{entryNumber:input.entryNumber}});return loadJournal(businessUnitId,id);}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
export async function updateJournal(userId:string,businessUnitId:string,journalId:string,input:UpdateJournalInput){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.write');const current=await loadJournal(businessUnitId,journalId);if(current.status!=='draft')throw new HttpError(409,'JOURNAL_LOCKED','Only draft journal entries can be modified.');const client=await pool.connect();try{await client.query('BEGIN');await client.query(`UPDATE journal_entries SET entry_date=$3,description=$4 WHERE id=$1 AND business_unit_id=$2`,[journalId,businessUnitId,input.entryDate??current.entryDate,input.description??current.description]);if(input.lines){await client.query('DELETE FROM journal_lines WHERE journal_entry_id=$1',[journalId]);await insertLines(client,journalId,input.lines);}await client.query('COMMIT');await writeAuditEvent({actorUserId:userId,legalEntityId:current.legalEntityId,businessUnitId,action:'bookkeeping.journal.updated',resourceType:'journal_entry',resourceId:journalId});return loadJournal(businessUnitId,journalId);}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
export async function postJournal(userId:string,businessUnitId:string,journalId:string){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.post');const current=await loadJournal(businessUnitId,journalId);if(current.status!=='draft')throw new HttpError(409,'JOURNAL_NOT_DRAFT','Only draft journal entries can be posted.');await pool.query(`UPDATE journal_entries SET status='posted' WHERE id=$1 AND business_unit_id=$2`,[journalId,businessUnitId]);await pool.query(`UPDATE accounting_events SET status='posted',journal_entry_id=$1,updated_at=now() WHERE business_unit_id=$2 AND source_type=COALESCE($3,source_type) AND source_id=COALESCE($4,source_id) AND status='pending'`,[journalId,businessUnitId,current.sourceType,current.sourceId]);await writeAuditEvent({actorUserId:userId,legalEntityId:current.legalEntityId,businessUnitId,action:'bookkeeping.journal.posted',resourceType:'journal_entry',resourceId:journalId});return loadJournal(businessUnitId,journalId);}
export async function reverseJournal(userId:string,businessUnitId:string,journalId:string,input:ReverseJournalInput){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.post');const original=await loadJournal(businessUnitId,journalId);if(original.status!=='posted')throw new HttpError(409,'JOURNAL_NOT_POSTED','Only posted journal entries can be reversed.');const context=await unitContext(businessUnitId);const client=await pool.connect();try{await client.query('BEGIN');const result=await client.query<{id:string}>(`INSERT INTO journal_entries (legal_entity_id,business_unit_id,entry_number,entry_date,description,reversed_entry_id,created_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[context.legal_entity_id,businessUnitId,input.entryNumber,input.entryDate,input.description??`Reversal of ${original.entryNumber}`,journalId,userId]);const reversalId=result.rows[0]?.id;if(!reversalId)throw new HttpError(500,'REVERSAL_CREATE_FAILED','Reversal entry could not be created.');for(const line of original.lines){await client.query(`INSERT INTO journal_lines (journal_entry_id,account_id,debit_cents,credit_cents,memo) VALUES ($1,$2,$3,$4,$5)`,[reversalId,line.accountId,line.creditCents,line.debitCents,`Reversal: ${line.memo??original.description}`]);}await client.query(`UPDATE journal_entries SET status='posted' WHERE id=$1`,[reversalId]);await client.query(`UPDATE journal_entries SET status='reversed' WHERE id=$1`,[journalId]);await client.query('COMMIT');await writeAuditEvent({actorUserId:userId,legalEntityId:context.legal_entity_id,businessUnitId,action:'bookkeeping.journal.reversed',resourceType:'journal_entry',resourceId:journalId,metadata:{reversalId}});return loadJournal(businessUnitId,reversalId);}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}

export async function listAccountingEvents(userId:string,businessUnitId:string,q:EventListQuery){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.read');const result=await pool.query<EventRow>(`SELECT id,event_type,source_type,source_id,amount_cents::text,status,journal_entry_id,metadata,created_at,updated_at FROM accounting_events WHERE business_unit_id=$1 AND ($2::text IS NULL OR status=$2) AND ($3::text IS NULL OR event_type=$3) ORDER BY created_at DESC LIMIT $4 OFFSET $5`,[businessUnitId,q.status??null,q.eventType??null,q.limit,q.offset]);return{data:result.rows.map(mapEvent),meta:paginationMeta(q,result.rows.length)};}
export async function postAccountingEvent(userId:string,businessUnitId:string,eventId:string,input:PostEventInput){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.post');const context=await unitContext(businessUnitId);const eventResult=await pool.query<EventRow>(`SELECT id,event_type,source_type,source_id,amount_cents::text,status,journal_entry_id,metadata,created_at,updated_at FROM accounting_events WHERE id=$1 AND business_unit_id=$2`,[eventId,businessUnitId]);const event=eventResult.rows[0];if(!event)throw new HttpError(404,'ACCOUNTING_EVENT_NOT_FOUND','Accounting event not found.');if(event.status!=='pending')throw new HttpError(409,'ACCOUNTING_EVENT_NOT_PENDING','Only pending accounting events can be posted.');const amount=event.amount_cents===null?0:Number(event.amount_cents);if(amount<=0)throw new HttpError(400,'ACCOUNTING_EVENT_AMOUNT_REQUIRED','Accounting event must have a positive amount to post.');const journal=await createJournal(userId,businessUnitId,{entryNumber:input.entryNumber,entryDate:input.entryDate,description:input.description??`${event.event_type}: ${event.source_type}`,sourceType:event.source_type,sourceId:event.source_id,lines:[{accountId:input.debitAccountId,debitCents:amount,creditCents:0,memo:null},{accountId:input.creditAccountId,debitCents:0,creditCents:amount,memo:null}]});await postJournal(userId,businessUnitId,journal.id);await pool.query(`UPDATE accounting_events SET status='posted',journal_entry_id=$2,updated_at=now() WHERE id=$1`,[eventId,journal.id]);await writeAuditEvent({actorUserId:userId,legalEntityId:context.legal_entity_id,businessUnitId,action:'bookkeeping.event.posted',resourceType:'accounting_event',resourceId:eventId,metadata:{journalEntryId:journal.id}});return{event:{...mapEvent(event),status:'posted',journalEntryId:journal.id},journal:await loadJournal(businessUnitId,journal.id)};}
