import type { z } from 'zod';
import { pool } from '../../db/pool.js';
import { HttpError } from '../../lib/http-error.js';
import { paginationMeta } from '../../lib/pagination.js';
import { assertBusinessUnitPermission } from '../access/authorization.service.js';
import { writeAuditEvent } from '../audit/admin-audit.service.js';
import { createJournal, postJournal } from './admin-bookkeeping.service.js';
import {
  createExpenseSchema, createRevenueSchema, expenseListQuerySchema, postExpenseSchema,
  postRevenueSchema, revenueListQuerySchema, updateExpenseSchema, updateRevenueSchema,
} from './admin-ledger-record.schemas.js';

type ExpenseListQuery=z.infer<typeof expenseListQuerySchema>;type CreateExpense=z.infer<typeof createExpenseSchema>;type UpdateExpense=z.infer<typeof updateExpenseSchema>;type PostExpense=z.infer<typeof postExpenseSchema>;
type RevenueListQuery=z.infer<typeof revenueListQuerySchema>;type CreateRevenue=z.infer<typeof createRevenueSchema>;type UpdateRevenue=z.infer<typeof updateRevenueSchema>;type PostRevenue=z.infer<typeof postRevenueSchema>;
type ExpenseRow={id:string;legal_entity_id:string;expense_date:string;vendor:string|null;description:string;amount_cents:string;expense_account_id:string|null;payment_account_id:string|null;journal_entry_id:string|null;status:'draft'|'posted'|'void';receipt_file_id:string|null;created_at:Date;updated_at:Date};
type RevenueRow={id:string;legal_entity_id:string;revenue_date:string;customer_id:string|null;description:string;amount_cents:string;revenue_account_id:string|null;deposit_account_id:string|null;journal_entry_id:string|null;status:'draft'|'posted'|'void';created_at:Date;updated_at:Date};
function mapExpense(r:ExpenseRow){return{id:r.id,legalEntityId:r.legal_entity_id,expenseDate:r.expense_date,vendor:r.vendor,description:r.description,amountCents:Number(r.amount_cents),expenseAccountId:r.expense_account_id,paymentAccountId:r.payment_account_id,journalEntryId:r.journal_entry_id,status:r.status,receiptFileId:r.receipt_file_id,createdAt:r.created_at,updatedAt:r.updated_at};}
function mapRevenue(r:RevenueRow){return{id:r.id,legalEntityId:r.legal_entity_id,revenueDate:r.revenue_date,customerId:r.customer_id,description:r.description,amountCents:Number(r.amount_cents),revenueAccountId:r.revenue_account_id,depositAccountId:r.deposit_account_id,journalEntryId:r.journal_entry_id,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at};}
async function entityId(businessUnitId:string){const r=await pool.query<{legal_entity_id:string}>('SELECT legal_entity_id FROM business_units WHERE id=$1',[businessUnitId]);const id=r.rows[0]?.legal_entity_id;if(!id)throw new HttpError(404,'BUSINESS_UNIT_NOT_FOUND','Business unit not found.');return id;}
async function validateFile(businessUnitId:string,fileId:string|null|undefined){if(!fileId)return;const r=await pool.query('SELECT 1 FROM files WHERE id=$1 AND business_unit_id=$2',[fileId,businessUnitId]);if(!r.rows[0])throw new HttpError(400,'INVALID_FILE','Receipt file does not belong to this business unit.');}
async function validateCustomer(businessUnitId:string,customerId:string|null|undefined){if(!customerId)return;const r=await pool.query('SELECT 1 FROM customers WHERE id=$1 AND business_unit_id=$2',[customerId,businessUnitId]);if(!r.rows[0])throw new HttpError(400,'INVALID_CUSTOMER','Customer does not belong to this business unit.');}
export async function listExpenses(userId:string,businessUnitId:string,q:ExpenseListQuery){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.read');const r=await pool.query<ExpenseRow>(`SELECT id,legal_entity_id,expense_date::text,vendor,description,amount_cents::text,expense_account_id,payment_account_id,journal_entry_id,status,receipt_file_id,created_at,updated_at FROM expenses WHERE business_unit_id=$1 AND ($2::text IS NULL OR status=$2) AND ($3::date IS NULL OR expense_date >= $3) AND ($4::date IS NULL OR expense_date <= $4) AND ($5::text IS NULL OR COALESCE(vendor,'') ILIKE '%'||$5||'%' OR description ILIKE '%'||$5||'%') ORDER BY expense_date DESC,created_at DESC LIMIT $6 OFFSET $7`,[businessUnitId,q.status??null,q.from??null,q.to??null,q.search||null,q.limit,q.offset]);return{data:r.rows.map(mapExpense),meta:paginationMeta(q,r.rows.length)};}
export async function createExpense(userId:string,businessUnitId:string,input:CreateExpense){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.write');await validateFile(businessUnitId,input.receiptFileId);const legalEntityId=await entityId(businessUnitId);const r=await pool.query<ExpenseRow>(`INSERT INTO expenses (legal_entity_id,business_unit_id,expense_date,vendor,description,amount_cents,expense_account_id,payment_account_id,receipt_file_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,legal_entity_id,expense_date::text,vendor,description,amount_cents::text,expense_account_id,payment_account_id,journal_entry_id,status,receipt_file_id,created_at,updated_at`,[legalEntityId,businessUnitId,input.expenseDate,input.vendor??null,input.description,input.amountCents,input.expenseAccountId??null,input.paymentAccountId??null,input.receiptFileId??null]);const row=r.rows[0];if(!row)throw new HttpError(500,'EXPENSE_CREATE_FAILED','Expense could not be created.');await writeAuditEvent({actorUserId:userId,legalEntityId,businessUnitId,action:'expense.created',resourceType:'expense',resourceId:row.id,metadata:{amountCents:input.amountCents}});return mapExpense(row);}
export async function updateExpense(userId:string,businessUnitId:string,expenseId:string,input:UpdateExpense){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.write');if(input.receiptFileId!==undefined)await validateFile(businessUnitId,input.receiptFileId);const r=await pool.query<ExpenseRow>(`SELECT id,legal_entity_id,expense_date::text,vendor,description,amount_cents::text,expense_account_id,payment_account_id,journal_entry_id,status,receipt_file_id,created_at,updated_at FROM expenses WHERE id=$1 AND business_unit_id=$2`,[expenseId,businessUnitId]);const c=r.rows[0];if(!c)throw new HttpError(404,'EXPENSE_NOT_FOUND','Expense not found.');if(c.status==='posted')throw new HttpError(409,'EXPENSE_LOCKED','Posted expenses cannot be edited.');const u=await pool.query<ExpenseRow>(`UPDATE expenses SET expense_date=$3,vendor=$4,description=$5,amount_cents=$6,expense_account_id=$7,payment_account_id=$8,receipt_file_id=$9,status=$10 WHERE id=$1 AND business_unit_id=$2 RETURNING id,legal_entity_id,expense_date::text,vendor,description,amount_cents::text,expense_account_id,payment_account_id,journal_entry_id,status,receipt_file_id,created_at,updated_at`,[expenseId,businessUnitId,input.expenseDate??c.expense_date,input.vendor===undefined?c.vendor:input.vendor,input.description??c.description,input.amountCents??Number(c.amount_cents),input.expenseAccountId===undefined?c.expense_account_id:input.expenseAccountId,input.paymentAccountId===undefined?c.payment_account_id:input.paymentAccountId,input.receiptFileId===undefined?c.receipt_file_id:input.receiptFileId,input.status??c.status]);const row=u.rows[0]!;await writeAuditEvent({actorUserId:userId,legalEntityId:c.legal_entity_id,businessUnitId,action:'expense.updated',resourceType:'expense',resourceId:expenseId,metadata:{status:row.status}});return mapExpense(row);}
export async function postExpense(userId:string,businessUnitId:string,expenseId:string,input:PostExpense){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.post');const r=await pool.query<ExpenseRow>(`SELECT id,legal_entity_id,expense_date::text,vendor,description,amount_cents::text,expense_account_id,payment_account_id,journal_entry_id,status,receipt_file_id,created_at,updated_at FROM expenses WHERE id=$1 AND business_unit_id=$2`,[expenseId,businessUnitId]);const e=r.rows[0];if(!e)throw new HttpError(404,'EXPENSE_NOT_FOUND','Expense not found.');if(e.status!=='draft')throw new HttpError(409,'EXPENSE_NOT_DRAFT','Only draft expenses can be posted.');if(!e.expense_account_id||!e.payment_account_id)throw new HttpError(400,'EXPENSE_ACCOUNTS_REQUIRED','Expense and payment accounts are required before posting.');const amount=Number(e.amount_cents);const journal=await createJournal(userId,businessUnitId,{entryNumber:input.entryNumber,entryDate:e.expense_date,description:e.description,sourceType:'expense',sourceId:e.id,lines:[{accountId:e.expense_account_id,debitCents:amount,creditCents:0,memo:e.vendor},{accountId:e.payment_account_id,debitCents:0,creditCents:amount,memo:e.vendor}]});const posted=await postJournal(userId,businessUnitId,journal.id);await pool.query(`UPDATE expenses SET status='posted',journal_entry_id=$3 WHERE id=$1 AND business_unit_id=$2`,[expenseId,businessUnitId,journal.id]);return{expense:{...mapExpense(e),status:'posted',journalEntryId:journal.id},journal:posted};}
export async function listRevenue(userId:string,businessUnitId:string,q:RevenueListQuery){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.read');const r=await pool.query<RevenueRow>(`SELECT id,legal_entity_id,revenue_date::text,customer_id,description,amount_cents::text,revenue_account_id,deposit_account_id,journal_entry_id,status,created_at,updated_at FROM revenue_records WHERE business_unit_id=$1 AND ($2::text IS NULL OR status=$2) AND ($3::date IS NULL OR revenue_date >= $3) AND ($4::date IS NULL OR revenue_date <= $4) AND ($5::uuid IS NULL OR customer_id=$5) AND ($6::text IS NULL OR description ILIKE '%'||$6||'%') ORDER BY revenue_date DESC,created_at DESC LIMIT $7 OFFSET $8`,[businessUnitId,q.status??null,q.from??null,q.to??null,q.customerId??null,q.search||null,q.limit,q.offset]);return{data:r.rows.map(mapRevenue),meta:paginationMeta(q,r.rows.length)};}
export async function createRevenue(userId:string,businessUnitId:string,input:CreateRevenue){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.write');await validateCustomer(businessUnitId,input.customerId);const legalEntityId=await entityId(businessUnitId);const r=await pool.query<RevenueRow>(`INSERT INTO revenue_records (legal_entity_id,business_unit_id,revenue_date,customer_id,description,amount_cents,revenue_account_id,deposit_account_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,legal_entity_id,revenue_date::text,customer_id,description,amount_cents::text,revenue_account_id,deposit_account_id,journal_entry_id,status,created_at,updated_at`,[legalEntityId,businessUnitId,input.revenueDate,input.customerId??null,input.description,input.amountCents,input.revenueAccountId??null,input.depositAccountId??null]);const row=r.rows[0];if(!row)throw new HttpError(500,'REVENUE_CREATE_FAILED','Revenue record could not be created.');await writeAuditEvent({actorUserId:userId,legalEntityId,businessUnitId,action:'revenue.created',resourceType:'revenue_record',resourceId:row.id,metadata:{amountCents:input.amountCents}});return mapRevenue(row);}
export async function updateRevenue(userId:string,businessUnitId:string,revenueId:string,input:UpdateRevenue){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.write');if(input.customerId!==undefined)await validateCustomer(businessUnitId,input.customerId);const r=await pool.query<RevenueRow>(`SELECT id,legal_entity_id,revenue_date::text,customer_id,description,amount_cents::text,revenue_account_id,deposit_account_id,journal_entry_id,status,created_at,updated_at FROM revenue_records WHERE id=$1 AND business_unit_id=$2`,[revenueId,businessUnitId]);const c=r.rows[0];if(!c)throw new HttpError(404,'REVENUE_NOT_FOUND','Revenue record not found.');if(c.status==='posted')throw new HttpError(409,'REVENUE_LOCKED','Posted revenue records cannot be edited.');const u=await pool.query<RevenueRow>(`UPDATE revenue_records SET revenue_date=$3,customer_id=$4,description=$5,amount_cents=$6,revenue_account_id=$7,deposit_account_id=$8,status=$9 WHERE id=$1 AND business_unit_id=$2 RETURNING id,legal_entity_id,revenue_date::text,customer_id,description,amount_cents::text,revenue_account_id,deposit_account_id,journal_entry_id,status,created_at,updated_at`,[revenueId,businessUnitId,input.revenueDate??c.revenue_date,input.customerId===undefined?c.customer_id:input.customerId,input.description??c.description,input.amountCents??Number(c.amount_cents),input.revenueAccountId===undefined?c.revenue_account_id:input.revenueAccountId,input.depositAccountId===undefined?c.deposit_account_id:input.depositAccountId,input.status??c.status]);const row=u.rows[0]!;await writeAuditEvent({actorUserId:userId,legalEntityId:c.legal_entity_id,businessUnitId,action:'revenue.updated',resourceType:'revenue_record',resourceId:revenueId,metadata:{status:row.status}});return mapRevenue(row);}
export async function postRevenue(userId:string,businessUnitId:string,revenueId:string,input:PostRevenue){await assertBusinessUnitPermission(userId,businessUnitId,'bookkeeping.post');const r=await pool.query<RevenueRow>(`SELECT id,legal_entity_id,revenue_date::text,customer_id,description,amount_cents::text,revenue_account_id,deposit_account_id,journal_entry_id,status,created_at,updated_at FROM revenue_records WHERE id=$1 AND business_unit_id=$2`,[revenueId,businessUnitId]);const e=r.rows[0];if(!e)throw new HttpError(404,'REVENUE_NOT_FOUND','Revenue record not found.');if(e.status!=='draft')throw new HttpError(409,'REVENUE_NOT_DRAFT','Only draft revenue records can be posted.');if(!e.revenue_account_id||!e.deposit_account_id)throw new HttpError(400,'REVENUE_ACCOUNTS_REQUIRED','Revenue and deposit accounts are required before posting.');const amount=Number(e.amount_cents);const journal=await createJournal(userId,businessUnitId,{entryNumber:input.entryNumber,entryDate:e.revenue_date,description:e.description,sourceType:'revenue_record',sourceId:e.id,lines:[{accountId:e.deposit_account_id,debitCents:amount,creditCents:0,memo:null},{accountId:e.revenue_account_id,debitCents:0,creditCents:amount,memo:null}]});const posted=await postJournal(userId,businessUnitId,journal.id);await pool.query(`UPDATE revenue_records SET status='posted',journal_entry_id=$3 WHERE id=$1 AND business_unit_id=$2`,[revenueId,businessUnitId,journal.id]);return{revenue:{...mapRevenue(e),status:'posted',journalEntryId:journal.id},journal:posted};}
