import type { z } from 'zod';
import { pool } from '../../db/pool.js';
import { HttpError } from '../../lib/http-error.js';
import { paginationMeta } from '../../lib/pagination.js';
import { writeAuditEvent } from '../audit/admin-audit.service.js';
import { notificationActionSchema, notificationListQuerySchema } from './admin-notification.schemas.js';

type ListQuery=z.infer<typeof notificationListQuerySchema>;type ActionInput=z.infer<typeof notificationActionSchema>;
type Row={id:string;channel:'email'|'webhook';recipient:string;template_key:string;subject:string|null;payload:Record<string,unknown>;status:'pending'|'processing'|'sent'|'failed'|'cancelled';attempts:number;available_at:Date;last_error:string|null;sent_at:Date|null;legal_entity_id:string|null;business_unit_id:string|null;created_at:Date;updated_at:Date};
function map(r:Row){return{id:r.id,channel:r.channel,recipient:r.recipient,templateKey:r.template_key,subject:r.subject,payload:r.payload,status:r.status,attempts:r.attempts,availableAt:r.available_at,lastError:r.last_error,sentAt:r.sent_at,legalEntityId:r.legal_entity_id,businessUnitId:r.business_unit_id,createdAt:r.created_at,updatedAt:r.updated_at};}
function accessSql(permission:string){return`EXISTS (SELECT 1 FROM user_role_assignments ura JOIN roles role ON role.id=ura.role_id JOIN role_permissions rp ON rp.role_id=role.id JOIN permissions p ON p.id=rp.permission_id LEFT JOIN business_units nbu ON nbu.id=n.business_unit_id WHERE ura.user_id=$1 AND p.key='${permission}' AND ((role.scope='platform' AND ura.legal_entity_id IS NULL AND ura.business_unit_id IS NULL) OR (n.legal_entity_id IS NOT NULL AND role.scope='legal_entity' AND ura.legal_entity_id=n.legal_entity_id) OR (n.business_unit_id IS NOT NULL AND ((role.scope='business_unit' AND ura.business_unit_id=n.business_unit_id) OR (role.scope='legal_entity' AND ura.legal_entity_id=nbu.legal_entity_id)))))`;}
export async function listNotifications(userId:string,q:ListQuery){const result=await pool.query<Row>(`SELECT n.id,n.channel,n.recipient,n.template_key,n.subject,n.payload,n.status,n.attempts,n.available_at,n.last_error,n.sent_at,n.legal_entity_id,n.business_unit_id,n.created_at,n.updated_at FROM notification_outbox n WHERE ${accessSql('notifications.read')} AND ($2::text IS NULL OR n.status=$2) AND ($3::text IS NULL OR n.channel=$3) AND ($4::text IS NULL OR n.template_key=$4) ORDER BY n.created_at DESC LIMIT $5 OFFSET $6`,[userId,q.status??null,q.channel??null,q.templateKey??null,q.limit,q.offset]);return{data:result.rows.map(map),meta:paginationMeta(q,result.rows.length)};}
export async function manageNotification(userId:string,notificationId:string,input:ActionInput){const result=await pool.query<Row>(`SELECT n.id,n.channel,n.recipient,n.template_key,n.subject,n.payload,n.status,n.attempts,n.available_at,n.last_error,n.sent_at,n.legal_entity_id,n.business_unit_id,n.created_at,n.updated_at FROM notification_outbox n WHERE n.id=$2 AND ${accessSql('notifications.manage')}`,[userId,notificationId]);const current=result.rows[0];if(!current)throw new HttpError(404,'NOTIFICATION_NOT_FOUND','Notification not found or not manageable in your scope.');if(input.action==='retry'){if(!['failed','cancelled'].includes(current.status))throw new HttpError(409,'NOTIFICATION_NOT_RETRYABLE','Only failed or cancelled notifications can be retried.');await pool.query(`UPDATE notification_outbox SET status='pending',available_at=now(),last_error=NULL WHERE id=$1`,[notificationId]);}else{if(['sent','cancelled'].includes(current.status))throw new HttpError(409,'NOTIFICATION_NOT_CANCELLABLE','Notification is already final.');await pool.query(`UPDATE notification_outbox SET status='cancelled' WHERE id=$1`,[notificationId]);}await writeAuditEvent({actorUserId:userId,legalEntityId:current.legal_entity_id,businessUnitId:current.business_unit_id,action:`notification.${input.action}`,resourceType:'notification_outbox',resourceId:notificationId});const updated=await pool.query<Row>(`SELECT id,channel,recipient,template_key,subject,payload,status,attempts,available_at,last_error,sent_at,legal_entity_id,business_unit_id,created_at,updated_at FROM notification_outbox WHERE id=$1`,[notificationId]);return map(updated.rows[0]!);}
