import type { z } from 'zod';
import { pool } from '../../db/pool.js';
import { HttpError } from '../../lib/http-error.js';
import { paginationMeta } from '../../lib/pagination.js';
import { assertBusinessUnitPermission, assertLegalEntityPermission, assertPlatformPermission } from '../access/authorization.service.js';
import { writeAuditEvent } from '../audit/admin-audit.service.js';
import { createIntegrationSchema, integrationListQuerySchema, updateIntegrationSchema } from './admin-integration.schemas.js';

type ListQuery=z.infer<typeof integrationListQuerySchema>;type CreateInput=z.infer<typeof createIntegrationSchema>;type UpdateInput=z.infer<typeof updateIntegrationSchema>;
type Row={id:string;scope:'platform'|'legal_entity'|'business_unit';legal_entity_id:string|null;business_unit_id:string|null;provider:string;integration_key:string;status:'active'|'inactive';config:Record<string,unknown>;secret_reference:string|null;created_at:Date;updated_at:Date};
function map(r:Row){return{id:r.id,scope:r.scope,legalEntityId:r.legal_entity_id,businessUnitId:r.business_unit_id,provider:r.provider,integrationKey:r.integration_key,status:r.status,config:r.config,hasSecretReference:r.secret_reference!==null,createdAt:r.created_at,updatedAt:r.updated_at};}
async function assertScope(userId:string,row:{scope:'platform'|'legal_entity'|'business_unit';legal_entity_id:string|null;business_unit_id:string|null},permission:string){if(row.scope==='platform')return assertPlatformPermission(userId,permission);if(row.scope==='legal_entity'&&row.legal_entity_id)return assertLegalEntityPermission(userId,row.legal_entity_id,permission);if(row.scope==='business_unit'&&row.business_unit_id)return assertBusinessUnitPermission(userId,row.business_unit_id,permission);throw new HttpError(400,'INVALID_INTEGRATION_SCOPE','Integration scope is invalid.');}
export async function listIntegrations(userId:string,q:ListQuery){const result=await pool.query<Row>(`SELECT i.id,i.scope,i.legal_entity_id,i.business_unit_id,i.provider,i.integration_key,i.status,i.config,i.secret_reference,i.created_at,i.updated_at FROM integration_settings i LEFT JOIN business_units ibu ON ibu.id=i.business_unit_id WHERE ($2::text IS NULL OR i.scope=$2) AND ($3::text IS NULL OR i.status=$3) AND ($4::text IS NULL OR i.provider=$4) AND EXISTS (SELECT 1 FROM user_role_assignments ura JOIN roles role ON role.id=ura.role_id JOIN role_permissions rp ON rp.role_id=role.id JOIN permissions p ON p.id=rp.permission_id WHERE ura.user_id=$1 AND p.key='integrations.read' AND ((i.scope='platform' AND role.scope='platform' AND ura.legal_entity_id IS NULL AND ura.business_unit_id IS NULL) OR (i.scope='legal_entity' AND role.scope='legal_entity' AND ura.legal_entity_id=i.legal_entity_id) OR (i.scope='business_unit' AND ((role.scope='business_unit' AND ura.business_unit_id=i.business_unit_id) OR (role.scope='legal_entity' AND ura.legal_entity_id=ibu.legal_entity_id) OR role.scope='platform')))) ORDER BY i.provider,i.integration_key LIMIT $5 OFFSET $6`,[userId,q.scope??null,q.status??null,q.provider??null,q.limit,q.offset]);return{data:result.rows.map(map),meta:paginationMeta(q,result.rows.length)};}
export async function createIntegration(userId:string,input:CreateInput){const scopeRow={scope:input.scope,legal_entity_id:input.legalEntityId??null,business_unit_id:input.businessUnitId??null};await assertScope(userId,scopeRow,'integrations.write');const result=await pool.query<Row>(`INSERT INTO integration_settings (scope,legal_entity_id,business_unit_id,provider,integration_key,status,config,secret_reference) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8) RETURNING id,scope,legal_entity_id,business_unit_id,provider,integration_key,status,config,secret_reference,created_at,updated_at`,[input.scope,input.legalEntityId??null,input.businessUnitId??null,input.provider,input.integrationKey,input.status,JSON.stringify(input.config),input.secretReference??null]);const row=result.rows[0];if(!row)throw new HttpError(500,'INTEGRATION_CREATE_FAILED','Integration could not be created.');await writeAuditEvent({actorUserId:userId,legalEntityId:row.legal_entity_id,businessUnitId:row.business_unit_id,action:'integration.created',resourceType:'integration_setting',resourceId:row.id,metadata:{provider:row.provider,integrationKey:row.integration_key}});return map(row);}
export async function updateIntegration(userId:string,integrationId:string,input:UpdateInput){const currentResult=await pool.query<Row>(`SELECT id,scope,legal_entity_id,business_unit_id,provider,integration_key,status,config,secret_reference,created_at,updated_at FROM integration_settings WHERE id=$1`,[integrationId]);const c=currentResult.rows[0];if(!c)throw new HttpError(404,'INTEGRATION_NOT_FOUND','Integration not found.');await assertScope(userId,c,'integrations.write');const result=await pool.query<Row>(`UPDATE integration_settings SET status=$2,config=$3::jsonb,secret_reference=$4 WHERE id=$1 RETURNING id,scope,legal_entity_id,business_unit_id,provider,integration_key,status,config,secret_reference,created_at,updated_at`,[integrationId,input.status??c.status,JSON.stringify(input.config??c.config),input.secretReference===undefined?c.secret_reference:input.secretReference]);const row=result.rows[0]!;await writeAuditEvent({actorUserId:userId,legalEntityId:row.legal_entity_id,businessUnitId:row.business_unit_id,action:'integration.updated',resourceType:'integration_setting',resourceId:integrationId,metadata:{provider:row.provider,status:row.status,secretReferenceChanged:input.secretReference!==undefined}});return map(row);}
