import type { z } from 'zod';
import { pool } from '../../db/pool.js';
import { HttpError } from '../../lib/http-error.js';
import { paginationMeta } from '../../lib/pagination.js';
import { assertBusinessUnitPermission } from '../access/authorization.service.js';
import { writeAuditEvent } from '../audit/admin-audit.service.js';
import { createVehicleSchema, updateVehicleSchema, vehicleListQuerySchema } from './admin-vehicle.schemas.js';

type ListQuery=z.infer<typeof vehicleListQuerySchema>;type CreateInput=z.infer<typeof createVehicleSchema>;type UpdateInput=z.infer<typeof updateVehicleSchema>;
type Row={id:string;name:string;year:number|null;make:string|null;model:string|null;vin:string|null;license_plate:string|null;current_odometer:string|null;status:'active'|'inactive'|'maintenance'|'retired';notes:string|null;created_at:Date;updated_at:Date};
function map(r:Row){return{id:r.id,name:r.name,year:r.year,make:r.make,model:r.model,vin:r.vin,licensePlate:r.license_plate,currentOdometer:r.current_odometer===null?null:Number(r.current_odometer),status:r.status,notes:r.notes,createdAt:r.created_at,updatedAt:r.updated_at};}
export async function listVehicles(userId:string,businessUnitId:string,q:ListQuery){await assertBusinessUnitPermission(userId,businessUnitId,'fleet.read');const result=await pool.query<Row>(`SELECT id,name,year,make,model,vin,license_plate,current_odometer::text,status,notes,created_at,updated_at FROM vehicles WHERE business_unit_id=$1 AND ($2::text IS NULL OR status=$2) AND ($3::text IS NULL OR name ILIKE '%'||$3||'%' OR COALESCE(make,'') ILIKE '%'||$3||'%' OR COALESCE(model,'') ILIKE '%'||$3||'%' OR COALESCE(vin,'') ILIKE '%'||$3||'%') ORDER BY name LIMIT $4 OFFSET $5`,[businessUnitId,q.status??null,q.search||null,q.limit,q.offset]);return{data:result.rows.map(map),meta:paginationMeta(q,result.rows.length)};}
export async function createVehicle(userId:string,businessUnitId:string,input:CreateInput){await assertBusinessUnitPermission(userId,businessUnitId,'fleet.write');const result=await pool.query<Row>(`INSERT INTO vehicles (business_unit_id,name,year,make,model,vin,license_plate,current_odometer,status,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,name,year,make,model,vin,license_plate,current_odometer::text,status,notes,created_at,updated_at`,[businessUnitId,input.name,input.year??null,input.make??null,input.model??null,input.vin??null,input.licensePlate??null,input.currentOdometer??null,input.status,input.notes??null]);const row=result.rows[0];if(!row)throw new HttpError(500,'VEHICLE_CREATE_FAILED','Vehicle could not be created.');await writeAuditEvent({actorUserId:userId,businessUnitId,action:'vehicle.created',resourceType:'vehicle',resourceId:row.id,metadata:{name:row.name}});return map(row);}
export async function updateVehicle(userId:string,businessUnitId:string,vehicleId:string,input:UpdateInput){await assertBusinessUnitPermission(userId,businessUnitId,'fleet.write');const currentResult=await pool.query<Row>(`SELECT id,name,year,make,model,vin,license_plate,current_odometer::text,status,notes,created_at,updated_at FROM vehicles WHERE id=$1 AND business_unit_id=$2`,[vehicleId,businessUnitId]);const c=currentResult.rows[0];if(!c)throw new HttpError(404,'VEHICLE_NOT_FOUND','Vehicle not found.');const result=await pool.query<Row>(`UPDATE vehicles SET name=$3,year=$4,make=$5,model=$6,vin=$7,license_plate=$8,current_odometer=$9,status=$10,notes=$11 WHERE id=$1 AND business_unit_id=$2 RETURNING id,name,year,make,model,vin,license_plate,current_odometer::text,status,notes,created_at,updated_at`,[vehicleId,businessUnitId,input.name??c.name,input.year===undefined?c.year:input.year,input.make===undefined?c.make:input.make,input.model===undefined?c.model:input.model,input.vin===undefined?c.vin:input.vin,input.licensePlate===undefined?c.license_plate:input.licensePlate,input.currentOdometer===undefined?(c.current_odometer===null?null:Number(c.current_odometer)):input.currentOdometer,input.status??c.status,input.notes===undefined?c.notes:input.notes]);const row=result.rows[0]!;await writeAuditEvent({actorUserId:userId,businessUnitId,action:'vehicle.updated',resourceType:'vehicle',resourceId:vehicleId,metadata:{status:row.status}});return map(row);}
